//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancoMainEntities1 : DbContext
    {
        public bancoMainEntities1()
            : base("name=bancoMainEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_CURSO> TB_CURSO { get; set; }
        public DbSet<TB_FACULDADE> TB_FACULDADE { get; set; }
        public DbSet<TB_MATERIA> TB_MATERIA { get; set; }
        public DbSet<TB_NOTA> TB_NOTA { get; set; }
        public DbSet<TB_NOTA_DES> TB_NOTA_DES { get; set; }
        public DbSet<TB_NOTA_IMG> TB_NOTA_IMG { get; set; }
        public DbSet<TB_NOTA_STR> TB_NOTA_STR { get; set; }
        public DbSet<TB_PICTURES> TB_PICTURES { get; set; }
        public DbSet<TB_USER> TB_USER { get; set; }
    }
}
