//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CURSO
    {
        public TB_CURSO()
        {
            this.TB_NOTA = new HashSet<TB_NOTA>();
        }
    
        public int CUR_INT_ID { get; set; }
        public string CUR_STR_NOME { get; set; }
        public int USER_INT_ID { get; set; }
    
        public virtual TB_USER TB_USER { get; set; }
        public virtual ICollection<TB_NOTA> TB_NOTA { get; set; }
    }
}
