//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NOTA_IMG
    {
        public int IMG_INT_ID { get; set; }
        public string IMG_STR_PATH { get; set; }
        public int NOTA_INT_ID { get; set; }
    
        public virtual TB_NOTA TB_NOTA { get; set; }
    }
}
