//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NOTA
    {
        public TB_NOTA()
        {
            this.TB_NOTA_DES = new HashSet<TB_NOTA_DES>();
            this.TB_NOTA_IMG = new HashSet<TB_NOTA_IMG>();
            this.TB_NOTA_STR = new HashSet<TB_NOTA_STR>();
        }
    
        public int NOTA_INT_ID { get; set; }
        public int FAC_INT_ID { get; set; }
        public int CUR_INT_ID { get; set; }
        public int MAT_INT_ID { get; set; }
        public int USER_INT_ID { get; set; }
    
        public virtual TB_CURSO TB_CURSO { get; set; }
        public virtual TB_FACULDADE TB_FACULDADE { get; set; }
        public virtual TB_MATERIA TB_MATERIA { get; set; }
        public virtual ICollection<TB_NOTA_DES> TB_NOTA_DES { get; set; }
        public virtual ICollection<TB_NOTA_IMG> TB_NOTA_IMG { get; set; }
        public virtual TB_USER TB_USER { get; set; }
        public virtual ICollection<TB_NOTA_STR> TB_NOTA_STR { get; set; }
    }
}
