//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NOTA
    {
        public int NOTA_INT_ID { get; set; }
        public int FAC_INT_ID { get; set; }
        public int CUR_INT_ID { get; set; }
        public int MAT_INT_ID { get; set; }
        public int USER_INT_ID { get; set; }
        public Nullable<int> STR_INT_ID { get; set; }
    
        public virtual TB_CURSO TB_CURSO { get; set; }
        public virtual TB_FACULDADE TB_FACULDADE { get; set; }
        public virtual TB_MATERIA TB_MATERIA { get; set; }
        public virtual TB_USER TB_USER { get; set; }
        public virtual TB_NOTA_STR TB_NOTA_STR { get; set; }
    }
}
