//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NOTA_STR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_NOTA_STR()
        {
            this.TB_NOTA = new HashSet<TB_NOTA>();
        }
    
        public int STR_INT_ID { get; set; }
        public string STR_STR_PATH { get; set; }
        public Nullable<int> NOTA_INT_ID { get; set; }
        public string STR_STR_TITLE { get; set; }
        public Nullable<int> STR_INT_AUTHOR { get; set; }
        public Nullable<int> STR_INT_EDITED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NOTA> TB_NOTA { get; set; }
        public virtual TB_NOTA TB_NOTA1 { get; set; }
        public virtual TB_USER TB_USER { get; set; }
        public virtual TB_USER TB_USER1 { get; set; }
    }
}
