//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NOTA_IMG
    {
        public int IMG_INT_ID { get; set; }
        public string IMG_STR_PATH { get; set; }
        public int NOTA_INT_ID { get; set; }
    
        public virtual TB_NOTA TB_NOTA { get; set; }
    }
}
