//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PICTURES
    {
        public int PIC_INT_ID { get; set; }
        public byte[] PIC_IMG_MAIN { get; set; }
        public int USER_INT_ID { get; set; }
    
        public virtual TB_USER TB_USER { get; set; }
    }
}
