//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PICTURES
    {
        public int PIC_INT_ID { get; set; }
        public byte[] PIC_IMG_MAIN { get; set; }
        public int USER_INT_ID { get; set; }
    
        public virtual TB_USER TB_USER { get; set; }
    }
}
