//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SHARE
    {
        public int SHARE_INT_ID { get; set; }
        public int NOTA_INT_ID { get; set; }
        public int RECIPIENT_INT_ID { get; set; }
        public int SENDER_INT_ID { get; set; }
    
        public virtual TB_USER TB_USER { get; set; }
        public virtual TB_USER TB_USER1 { get; set; }
    }
}
