//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_USER()
        {
            this.TB_CURSO = new HashSet<TB_CURSO>();
            this.TB_FACULDADE = new HashSet<TB_FACULDADE>();
            this.TB_MATERIA = new HashSet<TB_MATERIA>();
            this.TB_NOTA = new HashSet<TB_NOTA>();
            this.TB_PICTURES = new HashSet<TB_PICTURES>();
            this.TB_USER_FAC1 = new HashSet<TB_USER_FAC>();
            this.TB_USER_CUR = new HashSet<TB_USER_CUR>();
            this.TB_USER_MAT = new HashSet<TB_USER_MAT>();
        }
    
        public int USER_INT_ID { get; set; }
        public string USER_STR_NOME { get; set; }
        public int USER_INT_IDADE { get; set; }
        public string USER_STR_SEXO { get; set; }
        public string USER_STR_EMAIL { get; set; }
        public string USER_STR_SENHA { get; set; }
        public int USER_STR_FACEBOOKLOGIN { get; set; }
        public int USER_STR_GOOGLELOGIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CURSO> TB_CURSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_FACULDADE> TB_FACULDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MATERIA> TB_MATERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NOTA> TB_NOTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PICTURES> TB_PICTURES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USER_FAC> TB_USER_FAC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USER_CUR> TB_USER_CUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USER_MAT> TB_USER_MAT { get; set; }
    }
}
