//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        public TB_USER()
        {
            this.TB_CURSO = new HashSet<TB_CURSO>();
            this.TB_FACULDADE = new HashSet<TB_FACULDADE>();
            this.TB_MATERIA = new HashSet<TB_MATERIA>();
            this.TB_NOTA = new HashSet<TB_NOTA>();
            this.TB_PICTURES = new HashSet<TB_PICTURES>();
        }
    
        public int USER_INT_ID { get; set; }
        public string USER_STR_NOME { get; set; }
        public int USER_INT_IDADE { get; set; }
        public string USER_STR_SEXO { get; set; }
        public string USER_STR_EMAIL { get; set; }
        public string USER_STR_SENHA { get; set; }
        public int USER_STR_FACEBOOKLOGIN { get; set; }
        public int USER_STR_GOOGLELOGIN { get; set; }
    
        public virtual ICollection<TB_CURSO> TB_CURSO { get; set; }
        public virtual ICollection<TB_FACULDADE> TB_FACULDADE { get; set; }
        public virtual ICollection<TB_MATERIA> TB_MATERIA { get; set; }
        public virtual ICollection<TB_NOTA> TB_NOTA { get; set; }
        public virtual ICollection<TB_PICTURES> TB_PICTURES { get; set; }
    }
}
