CREATE DATABASE APP_TO_DO;

CREATE TABLE [dbo].[TB_USER]
(
    [USER_INT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [USER_STR_NOME] VARCHAR(150) NOT NULL, 
    [USER_INT_IDADE] INT NOT NULL, 
    [USER_STR_SEXO] VARCHAR(50) NOT NULL, 
    [USER_STR_EMAIL] VARCHAR(150) NOT NULL, 
    [USER_STR_SENHA] VARCHAR(50) NOT NULL, 
    [USER_STR_FACEBOOKLOGIN] INT NOT NULL, 
    [USER_STR_GOOGLELOGIN] INT NOT NULL
);

CREATE TABLE [dbo].[TB_FACULDADE]
(
    [FAC_INT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FAC_STR_NOME] VARCHAR(150) NOT NULL, 
    [FAC_USER_INT_ID_FK] INT NOT NULL,
    CONSTRAINT USER_INT_ID FOREIGN KEY (FAC_USER_INT_ID_FK) REFERENCES TB_USER(USER_INT_ID) 
);

CREATE TABLE [dbo].[TB_CURSO]
(
	[CUR_INT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CUR_STR_NOME] VARCHAR(150) NOT NULL, 
    [USER_INT_ID] INT NOT NULL,
	CONSTRAINT CUR_USER_INT_ID_FK FOREIGN KEY (USER_INT_ID) REFERENCES TB_USER(USER_INT_ID) 
);

CREATE TABLE [dbo].[TB_MATERIA]
(
	[MAT_INT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [MAT_STR_NOME] VARCHAR(150) NOT NULL, 
    [USER_INT_ID] INT NOT NULL, 
    [MAT_DATE_HORA] DATETIME NOT NULL,
	CONSTRAINT MAT_USER_INT_ID FOREIGN KEY (USER_INT_ID) REFERENCES TB_USER(USER_INT_ID) 
);

CREATE TABLE [dbo].[TB_NOTA]
(
	[NOTA_INT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FAC_INT_ID] INT NOT NULL, 
    [CUR_INT_ID] INT NOT NULL, 
    [MAT_INT_ID] INT NOT NULL, 
    [USER_INT_ID] INT NOT NULL,
	CONSTRAINT	NOTA_FAC_INT_ID_FK FOREIGN KEY (FAC_INT_ID) REFERENCES TB_FACULDADE(FAC_INT_ID),
	CONSTRAINT	NOTA_CUR_INT_ID_FK FOREIGN KEY (CUR_INT_ID) REFERENCES TB_CURSO(CUR_INT_ID),
	CONSTRAINT	NOTA_MAT_INT_ID_FK FOREIGN KEY (MAT_INT_ID) REFERENCES TB_MATERIA(MAT_INT_ID),
	CONSTRAINT	NOTA_USER_INT_ID_FK FOREIGN KEY (USER_INT_ID) REFERENCES TB_USER(USER_INT_ID) 



);


CREATE TABLE [dbo].[TB_NOTA_IMG]
(
	[IMG_INT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [IMG_STR_PATH] VARCHAR(150) NOT NULL, 
    [NOTA_INT_ID] INT NOT NULL,
	CONSTRAINT	IMG_USER_INT_ID FOREIGN KEY (NOTA_INT_ID) REFERENCES TB_NOTA(NOTA_INT_ID) 
);

CREATE TABLE [dbo].[TB_NOTA_STR]
(
	[STR_INT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [STR_STR_PATH] VARCHAR(150) NOT NULL, 
    [NOTA_INT_ID] INT NOT NULL,
	CONSTRAINT STR_USER_INT_ID FOREIGN KEY (NOTA_INT_ID) REFERENCES TB_NOTA(NOTA_INT_ID) 
);

CREATE TABLE [dbo].[TB_NOTA_DES]
(
	[DES_INT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [DES_STR_PATH] VARCHAR(150) NOT NULL, 
    [NOTA_INT_ID] INT NOT NULL,
	CONSTRAINT DES_USER_INT_ID FOREIGN KEY (NOTA_INT_ID) REFERENCES TB_NOTA(NOTA_INT_ID) 
);

select * from TB_NOTA_IMG


