CREATE TABLE [dbo].[TB_USER_CUR] (
    [USER_CUR_ID] INT IDENTITY (1, 1) NOT NULL,
    [CUR_INT_ID]  INT NOT NULL,
    [USER_INT_ID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([USER_CUR_ID] ASC),
    CONSTRAINT [USER_CUR_CUR_INT_ID_FK] FOREIGN KEY ([CUR_INT_ID]) REFERENCES [dbo].[TB_CURSO] ([CUR_INT_ID]),
    CONSTRAINT [USER_CUR_USER_INT_ID_FK] FOREIGN KEY ([USER_INT_ID]) REFERENCES [dbo].[TB_USER] ([USER_INT_ID])
);

CREATE TABLE [dbo].[TB_USER_FAC] (
    [USER_FAC_ID] INT IDENTITY (1, 1) NOT NULL,
    [FAC_INT_ID]  INT NOT NULL,
    [USER_INT_ID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([USER_FAC_ID] ASC),
    CONSTRAINT [USER-FAC_FAC_INT_ID_FK] FOREIGN KEY ([FAC_INT_ID]) REFERENCES [dbo].[TB_FACULDADE] ([FAC_INT_ID]),
    CONSTRAINT [USER-FAC_USER_INT_ID_FK] FOREIGN KEY ([USER_INT_ID]) REFERENCES [dbo].[TB_USER] ([USER_INT_ID])
);

CREATE TABLE [dbo].[TB_USER_MAT] (
    [USER_MAT_ID] INT IDENTITY (1, 1) NOT NULL,
    [MAT_INT_ID]  INT NOT NULL,
    [USER_INT_ID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([USER_MAT_ID] ASC),
    CONSTRAINT [USER_MAT_MAT_INT_ID_FK] FOREIGN KEY ([MAT_INT_ID]) REFERENCES [dbo].[TB_MATERIA] ([MAT_INT_ID]),
    CONSTRAINT [USER_MAT_USER_INT_ID_FK] FOREIGN KEY ([USER_INT_ID]) REFERENCES [dbo].[TB_USER] ([USER_INT_ID])
);

